# Agent-specific configuration
# Location `~/Library/Application\ Support/aichat/agents/Jarvis/config.yaml`

model: gemini:gemini-2.5-pro             # Specify the LLM to use
temperature: 1                # Set default temperature parameter, range (0, 1)
top_p: null                      # Set default top-p parameter, with a range of (0, 1) or (0, 2) depending on the model
use_tools: all                  # Which additional tools to use by agent. (e.g. 'fs,web_search')
agent_prelude: default              # Set a session to use when starting the agent. (e.g. temp, default)
instructions: summarize_prompt               # Override the instructions for the agent, have no effect for dynamic instructions
variables:                       # Custom default values for the agent variables
  <supports_function_calling>: <true>
  <supports_vision>: <true>
  <execute_command>: <true>
